backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "assets/img" # Media files will be stored in the repo under images/uploads

# Collections
collections:
  - name: "issue" # Used in routes, e.g., /admin/collections/blog
    label: "Issue" # Used in the UI
    folder: "_issue" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Nomor Issue", name: "category", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Gambar Sampul", name: "cover", widget: "image"}
      - {label: "Editorial", name: "body", widget: "markdown"}

  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Artikel" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Penulis", name: "author", widget: "string"}
      - {label: "Nomor Issue", name: "categories", widget: "string"}
